//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ligne_Telephonique
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ligne_Telephonique()
        {
            this.SMS = new HashSet<SMS>();
        }
    
        public string Numero { get; set; }
        public System.DateTime DateActivationGSM { get; set; }
        public string CodeAgence { get; set; }
        public bool EtatLigne { get; set; }
        public string Agence { get; set; }
        public string CIN { get; set; }
    
        public virtual Agence Agence1 { get; set; }
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMS> SMS { get; set; }
    }
}
