//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TPDataContext : DbContext
    {
        public TPDataContext()
            : base("name=TPDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Agence> Agence { get; set; }
        public virtual DbSet<Appel> Appel { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Ligne_Telephonique> Ligne_Telephonique { get; set; }
        public virtual DbSet<Recharge> Recharge { get; set; }
        public virtual DbSet<ServiceMovies> ServiceMovies { get; set; }
        public virtual DbSet<SMS> SMS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
